//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace task2_2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    public partial class Customer
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "First Name is required")]
        public string FName { get; set; }
        [Required(ErrorMessage = "Last Name is required")]
        public string LName { get; set; }

        [EmailAddress]
        public string Email { get; set; }
        [RegularExpression(@"^(079|078|077)\d{7,8}$", ErrorMessage = "Invalid jordanian phone number")]
        public string Phone { get; set; }
        [Range(18, 50, ErrorMessage = "your Age must be between 18 and 50")]
        public Nullable<int> Age { get; set; }
        [StringLength(10, ErrorMessage = "The JopTitle must be at most 10 characters long.")]
        public string JopTitle { get; set; }
        public Nullable<bool> Gender { get; set; }
    }
}
